import {useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import {supabase} from '../lib/api';
import {useApp} from '../lib/context';
export default function AuthModal(){
 const {t,authOpen,setAuthOpen,authMode,setAuthMode}=useApp();const navigate=useNavigate();
 const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');setNotice('');setBusy(true);const f=new FormData(e.currentTarget);const email=String(f.get('email')||'');const password=String(f.get('password')||'');
 try{if(authMode==='reset'){const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+'/belajar'});if(error)throw error;setNotice(t('Semak e-mel untuk pautan tetapan semula.','Check your email for a reset link.'));}
 else if(authMode==='recovery'){const {error}=await supabase.auth.updateUser({password});if(error)throw error;setNotice(t('Kata laluan telah dikemas kini.','Password updated.'));}
 else if(authMode==='signup'){const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin+'/belajar',data:{display_name:String(f.get('name')),form_level:Number(f.get('form'))}}});if(error)throw error;if(data.session){setAuthOpen(false);navigate('/belajar')}else setNotice(t('Pendaftaran diterima. Semak e-mel anda untuk mengesahkan akaun.','Registration received. Check your email to confirm your account.'));}
 else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;setAuthOpen(false);navigate('/belajar');}}
 catch(err){setError(err instanceof Error?err.message:t('Maaf, cuba lagi.','Sorry, please try again.'))}finally{setBusy(false)}}
 const change=(mode:typeof authMode)=>{setAuthMode(mode);setNotice('');setError('')};
 return <Dialog open={authOpen} onOpenChange={setAuthOpen}><DialogContent className="auth-dialog"><DialogTitle>{authMode==='signup'?t('Langkah pertama ke arah lebih faham.','Your first step towards understanding.'):authMode==='login'?t('Selamat kembali.','Welcome back.'):t('Tetapkan semula kata laluan','Reset your password')}</DialogTitle><DialogDescription>{t('Akaun percuma untuk menyimpan perbualan dan latihan anda.','A free account to save your conversations and practice.')}</DialogDescription><form onSubmit={submit} className="form-stack">{authMode==='signup'&&<><label>{t('Nama panggilan','Display name')}<input name="name" required maxLength={60} autoComplete="nickname"/></label><label>{t('Tingkatan','Form')}<select name="form"><option value="4">{t('Tingkatan 4','Form 4')}</option><option value="5">{t('Tingkatan 5','Form 5')}</option></select></label></>}{authMode!=='recovery'&&<label>{t('E-mel','Email')}<input name="email" type="email" required autoComplete="email"/></label>}{authMode!=='reset'&&<label>{t('Kata laluan','Password')}<input name="password" type="password" required minLength={8} maxLength={72} autoComplete={authMode==='login'?'current-password':'new-password'}/></label>}{authMode==='signup'&&<label className="consent"><input type="checkbox" required/>{t('Saya bersetuju dengan dasar privasi dan penggunaan data untuk akaun pembelajaran saya.','I agree to the privacy policy and use of my data for my learning account.')}</label>}{error&&<p className="error-text" role="alert">{error}</p>}{notice&&<p className="success-text" role="status">{notice}</p>}<button disabled={busy} className="button">{busy?t('Sebentar…','Please wait…'):authMode==='signup'?t('Cipta akaun percuma','Create free account'):authMode==='login'?t('Log masuk','Log in'):t('Teruskan','Continue')}</button></form><div className="auth-links">{authMode==='login'?<><button onClick={()=>change('signup')}>{t('Belum ada akaun? Daftar','New here? Sign up')}</button><button onClick={()=>change('reset')}>{t('Lupa kata laluan?','Forgot password?')}</button></>:<button onClick={()=>change('login')}>{t('Sudah ada akaun? Log masuk','Have an account? Log in')}</button>}</div></DialogContent></Dialog>;
}
